databaseChangeLog = {
	// include file: 'features/create-table-prueba.groovy'
	// include file: 'features/alter-table-prueba.groovy'
	include file: 'features/alter-table-product-v1.groovy'
	include file: 'features/create-table-orderhdr-v1.groovy'
	include file: 'features/alter-table-orderhdr-v1.groovy'
	include file: 'features/alter-table-orderhdr-v2.groovy'
	include file: 'features/create-table-orderitm-v1.groovy'
	include file: 'features/create-table-orderstatus-v1.groovy'
	include file: 'features/create-table-orderpayment-v1.groovy'
	include file: 'features/create-table-orderregform-v1.groovy'
	include file: 'features/alter-table-products-v2.groovy'
	include file: 'features/alter-table-registrationforms-v1.groovy'
	include file: 'features/alter-table-fieldlist-v1.groovy'
	include file: 'features/alter-table-registrationforms-v2.groovy'
	include file: 'features/alter-table-fieldlist-v2.groovy'
	include file: 'features/create-table-faq-v1.groovy'
	include file: 'features/alter-table-faq-v1.groovy'
	include file: 'features/create-table-relprodfaq-v1.groovy'
	include file: 'features/alter-table-relprodfaq-v1.groovy'
	include file: 'features/alter-table-products-v3.groovy'
	include file: 'features/create-table-reviews-v1.groovy'
	include file: 'features/create-table-reviews_values-v1.groovy'
	include file: 'features/insert-table-reviews_values-v1.groovy'

}
