databaseChangeLog = {
	include file: 'features/alter-table-orderhdr.groovy'
	include file: 'features/alter-table-orders-payment.groovy'
	include file: 'features/alter-table-products.groovy'
	include file: 'features/alter-table-clients.groovy'
	include file: 'features/alter-table-orderhdr-1.groovy'
	include file: 'features/alter-table-orderitm.groovy'
	include file: 'features/alter-table-orderspayment.groovy'
	include file: 'features/alter-table-orderhdr-2.groovy'
	include file: 'features/alter-table-clients-1.groovy'
	include file: 'features/add-config-1.groovy'
	include file: 'features/add-config-2.groovy'
	include file: 'features/alter-table-orderspayment2.groovy'
	include file: 'features/alter-table-review_values.groovy'
	include file: 'features/test-api-url.groovy'
	include file: 'features/alter-table-fieldlist.groovy'
	include file: 'features/alter-table-products-2.groovy'
	include file: 'features/alter-table-products-3.groovy'
	include file: 'features/alter-table-products-4.groovy'
	include file: 'features/alter-table-fieldlist-1.groovy'	
	include file: 'features/alter-table-registrationform.groovy'	
	include file: 'features/alter-table-faq.groovy'	
	include file: 'features/alter-table-rel_prod_faqs.groovy'
	include file: 'features/alter-table-products-5.groovy'
	include file: 'features/truncate-sessions.groovy'
	include file: 'features/truncate-auth_sessions.groovy'
	include file: 'features/truncate-clients.groovy'
	include file: 'features/truncate-config.groovy'
	include file: 'features/truncate-faqs.groovy'
	include file: 'features/truncate-features.groovy'
	include file: 'features/truncate-field_list.groovy'
	include file: 'features/truncate-login_errors.groovy'
	include file: 'features/truncate-orders_hdr.groovy'
	include file: 'features/truncate-orders_itm.groovy'
	include file: 'features/truncate-orders_payment.groovy'
	include file: 'features/truncate-orders_reg_forms.groovy'
	include file: 'features/truncate-products.groovy'
	include file: 'features/truncate-registration_forms.groovy'
	include file: 'features/truncate-rel_prod_faqs.groovy'
	include file: 'features/truncate-rel_prod_features.groovy'
	include file: 'features/truncate-reviews.groovy'
	include file: 'features/truncate-users.groovy'
	
	
	
	
}
