package features

databaseChangeLog = {

	changeSet(author: "German Middi", id: "insert-razas") {

		grailsChange {
			change {

				def lista = [
								[id_raza: 1, raza_tipo: "1", raza_txt: 'Afador', is_active:true],
								[id_raza: 2, raza_tipo: "1", raza_txt: 'Affenpinscher', is_active:true],
								[id_raza: 3, raza_tipo: "1", raza_txt: 'Airedale Terrier', is_active:true],
								[id_raza: 4, raza_tipo: "1", raza_txt: 'Akita Americano', is_active:true],
								[id_raza: 5, raza_tipo: "1", raza_txt: 'Alaskan Husky', is_active:true],
								[id_raza: 6, raza_tipo: "1", raza_txt: 'Alaskan Klee Kai', is_active:true],
								[id_raza: 7, raza_tipo: "1", raza_txt: 'Alaskan Malamute', is_active:true],
								[id_raza: 8, raza_tipo: "1", raza_txt: 'American Bulldog', is_active:true],
								[id_raza: 9, raza_tipo: "1", raza_txt: 'American Foxhound', is_active:true],
								[id_raza: 10, raza_tipo: "1", raza_txt: 'American Staffordshire Terrier', is_active:true],
								[id_raza: 11, raza_tipo: "1", raza_txt: 'Azawakh', is_active:true],
								[id_raza: 12, raza_tipo: "1", raza_txt: 'Barbet', is_active:true],
								[id_raza: 13, raza_tipo: "1", raza_txt: 'Basenji', is_active:true],
								[id_raza: 14, raza_tipo: "1", raza_txt: 'Basset Hound', is_active:true],
								[id_raza: 15, raza_tipo: "1", raza_txt: 'Beagle', is_active:true],
								[id_raza: 16, raza_tipo: "1", raza_txt: 'Beagle Harrier', is_active:true],
								[id_raza: 17, raza_tipo: "1", raza_txt: 'Beauceron', is_active:true],
								[id_raza: 18, raza_tipo: "1", raza_txt: 'Bedlington terrier', is_active:true],
								[id_raza: 19, raza_tipo: "1", raza_txt: 'Berger Picard', is_active:true],
								[id_raza: 20, raza_tipo: "1", raza_txt: 'Bichón Boloñés', is_active:true],
								[id_raza: 21, raza_tipo: "1", raza_txt: 'Bichón Frisé', is_active:true],
								[id_raza: 22, raza_tipo: "1", raza_txt: 'Bichón Habanero', is_active:true],
								[id_raza: 23, raza_tipo: "1", raza_txt: 'Bichón Maltés', is_active:true],
								[id_raza: 24, raza_tipo: "1", raza_txt: 'Black and Tan Coonhound', is_active:true],
								[id_raza: 25, raza_tipo: "1", raza_txt: 'Bloodhound', is_active:true],
								[id_raza: 26, raza_tipo: "1", raza_txt: 'Boerboel', is_active:true],
								[id_raza: 27, raza_tipo: "1", raza_txt: 'Border Collie', is_active:true],
								[id_raza: 28, raza_tipo: "1", raza_txt: 'Border Terrier', is_active:true],
								[id_raza: 29, raza_tipo: "1", raza_txt: 'Borzoi', is_active:true],
								[id_raza: 30, raza_tipo: "1", raza_txt: 'Boston Terrier', is_active:true],
								[id_raza: 31, raza_tipo: "1", raza_txt: 'Bóxer', is_active:true],
								[id_raza: 32, raza_tipo: "1", raza_txt: 'Boyero de Berna', is_active:true],
								[id_raza: 33, raza_tipo: "1", raza_txt: 'Braco Alemán de Pelo Corto', is_active:true],
								[id_raza: 34, raza_tipo: "1", raza_txt: 'Braco Alemán de pelo Duro', is_active:true],
								[id_raza: 35, raza_tipo: "1", raza_txt: 'Braco Italiano', is_active:true],
								[id_raza: 36, raza_tipo: "1", raza_txt: 'Buhund Noruego', is_active:true],
								[id_raza: 37, raza_tipo: "1", raza_txt: 'Bulldog Francés', is_active:true],
								[id_raza: 38, raza_tipo: "1", raza_txt: 'Bulldog Inglés', is_active:true],
								[id_raza: 39, raza_tipo: "1", raza_txt: 'Bullmastiff', is_active:true],
								[id_raza: 40, raza_tipo: "1", raza_txt: 'Bull Terrier', is_active:true],
								[id_raza: 41, raza_tipo: "1", raza_txt: 'Bull Terrier Miniatura ', is_active:true],
								[id_raza: 42, raza_tipo: "1", raza_txt: 'Pug o Carlino', is_active:true],
								[id_raza: 43, raza_tipo: "1", raza_txt: 'Canaan dog', is_active:true],
								[id_raza: 44, raza_tipo: "1", raza_txt: 'Caniche Mediano', is_active:true],
								[id_raza: 45, raza_tipo: "1", raza_txt: 'Caniche Miniatura', is_active:true],
								[id_raza: 46, raza_tipo: "1", raza_txt: 'Cairn Terrier', is_active:true],
								[id_raza: 47, raza_tipo: "1", raza_txt: 'Catahoula Leopard Dog', is_active:true],
								[id_raza: 48, raza_tipo: "1", raza_txt: 'Chihuahua', is_active:true],
								[id_raza: 49, raza_tipo: "1", raza_txt: 'Chin Japonés', is_active:true],
								[id_raza: 50, raza_tipo: "1", raza_txt: 'Chinook', is_active:true],
								[id_raza: 51, raza_tipo: "1", raza_txt: 'Chow Chow', is_active:true],
								[id_raza: 52, raza_tipo: "1", raza_txt: 'Clumber Spaniel', is_active:true],
								[id_raza: 53, raza_tipo: "1", raza_txt: 'Cocker Spaniel Americano', is_active:true],
								[id_raza: 54, raza_tipo: "1", raza_txt: 'Cocker Spaniel Inglés', is_active:true],
								[id_raza: 55, raza_tipo: "1", raza_txt: 'Collie', is_active:true],
								[id_raza: 56, raza_tipo: "1", raza_txt: 'Collie barbudo o bearded collie', is_active:true],
								[id_raza: 57, raza_tipo: "1", raza_txt: 'Corgi Galés de Cardigan', is_active:true],
								[id_raza: 58, raza_tipo: "1", raza_txt: 'Corgi Galés de Pembroke', is_active:true],
								[id_raza: 59, raza_tipo: "1", raza_txt: 'Cotón de Tuléar', is_active:true],
								[id_raza: 60, raza_tipo: "1", raza_txt: 'Curly-Coated Retriever', is_active:true],
								[id_raza: 61, raza_tipo: "1", raza_txt: 'Dachshund', is_active:true],
								[id_raza: 62, raza_tipo: "1", raza_txt: 'Dálmata', is_active:true],
								[id_raza: 63, raza_tipo: "1", raza_txt: 'Dandie Dinmont Terrier', is_active:true],
								[id_raza: 64, raza_tipo: "1", raza_txt: 'Dingo Australiano', is_active:true],
								[id_raza: 65, raza_tipo: "1", raza_txt: 'Dóberman', is_active:true],
								[id_raza: 66, raza_tipo: "1", raza_txt: 'Dogo Argentino', is_active:true],
								[id_raza: 67, raza_tipo: "1", raza_txt: 'Dogo de Burdeos', is_active:true],
								[id_raza: 68, raza_tipo: "1", raza_txt: 'Dutch Shepherd', is_active:true],
								[id_raza: 69, raza_tipo: "1", raza_txt: 'Elkhound Noruego', is_active:true],
								[id_raza: 70, raza_tipo: "1", raza_txt: 'Field Spaniel', is_active:true],
								[id_raza: 71, raza_tipo: "1", raza_txt: 'Finnish Spitz', is_active:true],
								[id_raza: 72, raza_tipo: "1", raza_txt: 'Flat-Coated Retriever', is_active:true],
								[id_raza: 73, raza_tipo: "1", raza_txt: 'Foxhound Inglés', is_active:true],
								[id_raza: 74, raza_tipo: "1", raza_txt: 'Fox Terrier', is_active:true],
								[id_raza: 75, raza_tipo: "1", raza_txt: 'Fox Terrier Toy', is_active:true],
								[id_raza: 76, raza_tipo: "1", raza_txt: 'Galgo Afgano', is_active:true],
								[id_raza: 77, raza_tipo: "1", raza_txt: 'Galgo Español', is_active:true],
								[id_raza: 78, raza_tipo: "1", raza_txt: 'Galgo Italiano', is_active:true],
								[id_raza: 79, raza_tipo: "1", raza_txt: 'Glen of Imaal Terrier', is_active:true],
								[id_raza: 80, raza_tipo: "1", raza_txt: 'Golden Retriever', is_active:true],
								[id_raza: 81, raza_tipo: "1", raza_txt: 'Gran Boyero Suizo', is_active:true],
								[id_raza: 82, raza_tipo: "1", raza_txt: 'Gran Danés', is_active:true],
								[id_raza: 83, raza_tipo: "1", raza_txt: 'Grifón de Bruselas', is_active:true],
								[id_raza: 84, raza_tipo: "1", raza_txt: 'Grifón vandeano basset pequeño', is_active:true],
								[id_raza: 85, raza_tipo: "1", raza_txt: 'Hamiltonstovare', is_active:true],
								[id_raza: 86, raza_tipo: "1", raza_txt: 'Harrier', is_active:true],
								[id_raza: 87, raza_tipo: "1", raza_txt: 'Hokkaido Inu', is_active:true],
								[id_raza: 88, raza_tipo: "1", raza_txt: 'Husky Siberiano', is_active:true],
								[id_raza: 89, raza_tipo: "1", raza_txt: 'Jack Russell Terrier', is_active:true],
								[id_raza: 90, raza_tipo: "1", raza_txt: 'Japanese Spitz', is_active:true],
								[id_raza: 91, raza_tipo: "1", raza_txt: 'Karelian Bear', is_active:true],
								[id_raza: 92, raza_tipo: "1", raza_txt: 'Keeshond', is_active:true],
								[id_raza: 93, raza_tipo: "1", raza_txt: 'Kerry Blue Terrier', is_active:true],
								[id_raza: 94, raza_tipo: "1", raza_txt: 'Komondor', is_active:true],
								[id_raza: 95, raza_tipo: "1", raza_txt: 'Korean Jindo', is_active:true],
								[id_raza: 96, raza_tipo: "1", raza_txt: 'Kuvasz', is_active:true],
								[id_raza: 97, raza_tipo: "1", raza_txt: 'Labradoodle', is_active:true],
								[id_raza: 98, raza_tipo: "1", raza_txt: 'Labrador Retriever', is_active:true],
								[id_raza: 99, raza_tipo: "1", raza_txt: 'Lagotto Romagnolo', is_active:true],
								[id_raza: 100, raza_tipo: "1", raza_txt: 'Lakeland Terrier', is_active: true],
								[id_raza: 101, raza_tipo: "1", raza_txt: 'Lancashire Heeler', is_active: true],
								[id_raza: 102, raza_tipo: "1", raza_txt: 'Leonberger', is_active: true],
								[id_raza: 103, raza_tipo: "1", raza_txt: 'Lhasa Apso', is_active: true],
								[id_raza: 104, raza_tipo: "1", raza_txt: 'Manchester Terrier', is_active: true],
								[id_raza: 105, raza_tipo: "1", raza_txt: 'Mastín', is_active: true],
								[id_raza: 106, raza_tipo: "1", raza_txt: 'Mastín Afgano', is_active: true],
								[id_raza: 107, raza_tipo: "1", raza_txt: 'Mastín Español', is_active: true],
								[id_raza: 108, raza_tipo: "1", raza_txt: 'Mastín Italiano', is_active: true],
								[id_raza: 109, raza_tipo: "1", raza_txt: 'Mastín Napolitano', is_active: true],
								[id_raza: 110, raza_tipo: "1", raza_txt: 'Mastín Tibetano', is_active: true],
								[id_raza: 111, raza_tipo: "1", raza_txt: 'Mucuchíes', is_active: true],
								[id_raza: 112, raza_tipo: "1", raza_txt: 'Mudi', is_active: true],
								[id_raza: 113, raza_tipo: "1", raza_txt: 'Münsterländer Grande', is_active: true],
								[id_raza: 114, raza_tipo: "1", raza_txt: 'Otterhound', is_active: true],
								[id_raza: 115, raza_tipo: "1", raza_txt: 'Ovejero Magallánico', is_active: true],
								[id_raza: 116, raza_tipo: "1", raza_txt: 'Papillon', is_active: true],
								[id_raza: 117, raza_tipo: "1", raza_txt: 'Parson Russell Terrier', is_active: true],
								[id_raza: 118, raza_tipo: "1", raza_txt: 'Pastor Alemán', is_active: true],
								[id_raza: 119, raza_tipo: "1", raza_txt: 'Pastor Belga', is_active: true],
								[id_raza: 120, raza_tipo: "1", raza_txt: 'Pastor Belga Groenendael', is_active: true],
								[id_raza: 121, raza_tipo: "1", raza_txt: 'Pastor Belga Laekenois', is_active: true],
								[id_raza: 122, raza_tipo: "1", raza_txt: 'Pastor Belga Malinois', is_active: true],
								[id_raza: 123, raza_tipo: "1", raza_txt: 'Pastor Belga Tervuerense', is_active: true],
								[id_raza: 124, raza_tipo: "1", raza_txt: 'Pastor Blanco Suizo', is_active: true],
								[id_raza: 125, raza_tipo: "1", raza_txt: 'Pastor Catalán', is_active: true],
								[id_raza: 126, raza_tipo: "1", raza_txt: 'Pastor Chiribaya o Pastor Peruano', is_active: true],
								[id_raza: 127, raza_tipo: "1", raza_txt: 'Pastor Croata', is_active: true],
								[id_raza: 128, raza_tipo: "1", raza_txt: 'Pastor de Anatolia', is_active: true],
								[id_raza: 129, raza_tipo: "1", raza_txt: 'Pastor de Briep', is_active: true],
								[id_raza: 130, raza_tipo: "1", raza_txt: 'Pastor de Karst', is_active: true],
								[id_raza: 131, raza_tipo: "1", raza_txt: 'Pastor de las islas Shetland', is_active: true],
								[id_raza: 132, raza_tipo: "1", raza_txt: 'Pastor de los Pirineos', is_active: true],
								[id_raza: 133, raza_tipo: "1", raza_txt: 'Pastor del Cáucaso', is_active: true],
								[id_raza: 134, raza_tipo: "1", raza_txt: 'Pastor de Rusia Meridional', is_active: true],
								[id_raza: 135, raza_tipo: "1", raza_txt: 'Pastor Ganadero Australiano', is_active: true],
								[id_raza: 136, raza_tipo: "1", raza_txt: 'Pastor Garafiano', is_active: true],
								[id_raza: 137, raza_tipo: "1", raza_txt: 'Pastor Islandés', is_active: true],
								[id_raza: 138, raza_tipo: "1", raza_txt: 'Pastor Lapón', is_active: true],
								[id_raza: 139, raza_tipo: "1", raza_txt: 'Pastor Lapón de Suecia', is_active: true],
								[id_raza: 140, raza_tipo: "1", raza_txt: 'Pastor Leonés', is_active: true],
								[id_raza: 141, raza_tipo: "1", raza_txt: 'Pastor Mallorquín', is_active: true],
								[id_raza: 142, raza_tipo: "1", raza_txt: 'Pastor Ovejero Australiano', is_active: true],
								[id_raza: 143, raza_tipo: "1", raza_txt: 'Pastor Polaco de las Llanuras', is_active: true],
								[id_raza: 144, raza_tipo: "1", raza_txt: 'Pastor Polaco de Podhale', is_active: true],
								[id_raza: 145, raza_tipo: "1", raza_txt: 'Pastor Portugués', is_active: true],
								[id_raza: 146, raza_tipo: "1", raza_txt: 'Pastor Vasco', is_active: true],
								[id_raza: 147, raza_tipo: "1", raza_txt: 'Pastor Yugoslavo de Charplanina', is_active: true],
								[id_raza: 148, raza_tipo: "1", raza_txt: 'Pequeño Brabazón', is_active: true],
								[id_raza: 149, raza_tipo: "1", raza_txt: 'Pekinés', is_active: true],
								[id_raza: 150, raza_tipo: "1", raza_txt: 'Perdiguero de Burgos', is_active: true],
								[id_raza: 151, raza_tipo: "1", raza_txt: 'Perdiguero de Dentre', is_active: true],
								[id_raza: 152, raza_tipo: "1", raza_txt: 'Perdiguero Portugués', is_active: true],
								[id_raza: 153, raza_tipo: "1", raza_txt: 'Perro de Agua Español', is_active: true],
								[id_raza: 154, raza_tipo: "1", raza_txt: 'Perro de Agua Frisón', is_active: true],
								[id_raza: 155, raza_tipo: "1", raza_txt: 'Perro de Aguas Portugués', is_active: true],
								[id_raza: 156, raza_tipo: "1", raza_txt: 'Perro de Canaan', is_active: true],
								[id_raza: 157, raza_tipo: "1", raza_txt: 'Perro Crestado Chino', is_active: true],
								[id_raza: 158, raza_tipo: "1", raza_txt: 'Perro de Agua Americano', is_active: true],
								[id_raza: 159, raza_tipo: "1", raza_txt: 'Perro de Groenlandia', is_active: true],
								[id_raza: 160, raza_tipo: "1", raza_txt: 'Perro de Montaña de los Pirineos', is_active: true],
								[id_raza: 161, raza_tipo: "1", raza_txt: 'Perro del Atlas', is_active: true],
								[id_raza: 162, raza_tipo: "1", raza_txt: 'Perro Esquimal Americano', is_active: true],
								[id_raza: 163, raza_tipo: "1", raza_txt: 'Perro Esquimal Canadiense', is_active: true],
								[id_raza: 164, raza_tipo: "1", raza_txt: 'Perro Hiena', is_active: true],
								[id_raza: 165, raza_tipo: "1", raza_txt: 'Perro Lobo Chescolovaco', is_active: true],
								[id_raza: 166, raza_tipo: "1", raza_txt: 'Perro Lobo de Saarlos', is_active: true],
								[id_raza: 167, raza_tipo: "1", raza_txt: 'Perro Lobo Herreño', is_active: true],
								[id_raza: 168, raza_tipo: "1", raza_txt: 'Perro Majorero', is_active: true],
								[id_raza: 169, raza_tipo: "1", raza_txt: 'Perro sin pelo Mexicano', is_active: true],
								[id_raza: 170, raza_tipo: "1", raza_txt: 'Phalène', is_active: true],
								[id_raza: 171, raza_tipo: "1", raza_txt: 'Pinscher', is_active: true],
								[id_raza: 172, raza_tipo: "1", raza_txt: 'Pinscher Austriaco', is_active: true],
								[id_raza: 173, raza_tipo: "1", raza_txt: 'Pinscher Miniatura', is_active: true],
								[id_raza: 174, raza_tipo: "1", raza_txt: 'Pit bull terrier americano', is_active: true],
								[id_raza: 175, raza_tipo: "1", raza_txt: 'Podenco Andaluz', is_active: true],
								[id_raza: 176, raza_tipo: "1", raza_txt: 'Podenco Canario', is_active: true],
								[id_raza: 177, raza_tipo: "1", raza_txt: 'Podenco Ibicenco', is_active: true],
								[id_raza: 178, raza_tipo: "1", raza_txt: 'Podenco Portugués', is_active: true],
								[id_raza: 179, raza_tipo: "1", raza_txt: 'Pointer', is_active: true],
								[id_raza: 180, raza_tipo: "1", raza_txt: 'Pointer Inglés', is_active: true],
								[id_raza: 181, raza_tipo: "1", raza_txt: 'Pomerania', is_active: true],
								[id_raza: 182, raza_tipo: "1", raza_txt: 'Porcelain', is_active: true],
								[id_raza: 183, raza_tipo: "1", raza_txt: 'Presa Canario', is_active: true],
								[id_raza: 184, raza_tipo: "1", raza_txt: 'Pudelpointer', is_active: true],
								[id_raza: 185, raza_tipo: "1", raza_txt: 'Puli', is_active: true],
								[id_raza: 186, raza_tipo: "1", raza_txt: 'Raad van Beheer', is_active: true],
								[id_raza: 187, raza_tipo: "1", raza_txt: 'Rastreadores de Hannover ', is_active: true],
								[id_raza: 188, raza_tipo: "1", raza_txt: 'Rastreador Montañés de Baviera', is_active: true],
								[id_raza: 189, raza_tipo: "1", raza_txt: 'Rata Terrier', is_active: true],
								[id_raza: 190, raza_tipo: "1", raza_txt: 'Ratonero Bodeguero Andaluz', is_active: true],
								[id_raza: 191, raza_tipo: "1", raza_txt: 'Ratonero de Praga', is_active: true],
								[id_raza: 192, raza_tipo: "1", raza_txt: 'Ratonero Mallorquín', is_active: true],
								[id_raza: 193, raza_tipo: "1", raza_txt: 'Ratonero Valenciano', is_active: true],
								[id_raza: 194, raza_tipo: "1", raza_txt: 'Redbone Coonhound', is_active: true],
								[id_raza: 195, raza_tipo: "1", raza_txt: 'Retriever de la Bahía de Chesapeake', is_active: true],
								[id_raza: 196, raza_tipo: "1", raza_txt: 'Retriever de Pelo Liso', is_active: true],
								[id_raza: 197, raza_tipo: "1", raza_txt: 'Rottweiler', is_active: true],
								[id_raza: 198, raza_tipo: "1", raza_txt: 'Sabueso Alemán', is_active: true],
								[id_raza: 199, raza_tipo: "1", raza_txt: 'Sabueso Artesiano', is_active: true],
								[id_raza: 200, raza_tipo: "1", raza_txt: 'Sabueso Austriaco Negro y Fuego', is_active: true],
								[id_raza: 201, raza_tipo: "1", raza_txt: 'Sabueso Bosnio de Pelo Cerdoso', is_active: true],
								[id_raza: 202, raza_tipo: "1", raza_txt: 'Sabueso del Tirol', is_active: true],
								[id_raza: 203, raza_tipo: "1", raza_txt: 'Sabueso de Hygen', is_active: true],
								[id_raza: 204, raza_tipo: "1", raza_txt: 'Sabueso de las Montañas de Montenegro', is_active: true],
								[id_raza: 205, raza_tipo: "1", raza_txt: 'Sabueso Eslovaco', is_active: true],
								[id_raza: 206, raza_tipo: "1", raza_txt: 'Sabueso Español', is_active: true],
								[id_raza: 207, raza_tipo: "1", raza_txt: 'Sabueso Finlandés', is_active: true],
								[id_raza: 208, raza_tipo: "1", raza_txt: 'Sabueso Francés Tricolor', is_active: true],
								[id_raza: 209, raza_tipo: "1", raza_txt: 'Sabueso Halden', is_active: true],
								[id_raza: 210, raza_tipo: "1", raza_txt: 'Sabueso Italiano de Pelo Corto', is_active: true],
								[id_raza: 211, raza_tipo: "1", raza_txt: 'Sabueso Italiano de Pelo Duro', is_active: true],
								[id_raza: 212, raza_tipo: "1", raza_txt: 'Sabueso Noruego', is_active: true],
								[id_raza: 213, raza_tipo: "1", raza_txt: 'Sabueso Polaco', is_active: true],
								[id_raza: 214, raza_tipo: "1", raza_txt: 'Sabueso Schiller', is_active: true],
								[id_raza: 215, raza_tipo: "1", raza_txt: 'Sabueso Serbio', is_active: true],
								[id_raza: 216, raza_tipo: "1", raza_txt: 'Sabueso Suizo', is_active: true],
								[id_raza: 217, raza_tipo: "1", raza_txt: 'Sabueso Tinajero', is_active: true],
								[id_raza: 218, raza_tipo: "1", raza_txt: 'Sabueso Tricolor Serbio', is_active: true],
								[id_raza: 219, raza_tipo: "1", raza_txt: 'Saluki', is_active: true],
								[id_raza: 220, raza_tipo: "1", raza_txt: 'Samoyedo', is_active: true],
								[id_raza: 221, raza_tipo: "1", raza_txt: 'San Bernardo', is_active: true],
								[id_raza: 222, raza_tipo: "1", raza_txt: 'Schapendoes Neerlandés', is_active: true],
								[id_raza: 223, raza_tipo: "1", raza_txt: 'Schipperke', is_active: true],
								[id_raza: 224, raza_tipo: "1", raza_txt: 'Schnauzer', is_active: true],
								[id_raza: 225, raza_tipo: "1", raza_txt: 'Schnauzer Blanco', is_active: true],
								[id_raza: 226, raza_tipo: "1", raza_txt: 'Schnauzer Gigante', is_active: true],
								[id_raza: 227, raza_tipo: "1", raza_txt: 'Schanauzer Miniatura', is_active: true],
								[id_raza: 228, raza_tipo: "1", raza_txt: 'Sealyham Terrier', is_active: true],
								[id_raza: 229, raza_tipo: "1", raza_txt: 'Setter Gordon', is_active: true],
								[id_raza: 230, raza_tipo: "1", raza_txt: 'Setter Inglés', is_active: true],
								[id_raza: 231, raza_tipo: "1", raza_txt: 'Setter Irlandés', is_active: true],
								[id_raza: 232, raza_tipo: "1", raza_txt: 'Setter Irlandés Rojo', is_active: true],
								[id_raza: 233, raza_tipo: "1", raza_txt: 'Setter Irlandés Rojo y Blanco', is_active: true],
								[id_raza: 234, raza_tipo: "1", raza_txt: 'Shar Pei', is_active: true],
								[id_raza: 235, raza_tipo: "1", raza_txt: 'Shiba Inu', is_active: true],
								[id_raza: 236, raza_tipo: "1", raza_txt: 'Shikoku Inu', is_active: true],
								[id_raza: 237, raza_tipo: "1", raza_txt: 'Shih Tzu', is_active: true],
								[id_raza: 238, raza_tipo: "1", raza_txt: 'Silky Terrier Australiano', is_active: true],
								[id_raza: 239, raza_tipo: "1", raza_txt: 'Spaniel Bretón', is_active: true],
								[id_raza: 240, raza_tipo: "1", raza_txt: 'Spaniel Continental Enanos', is_active: true],
								[id_raza: 241, raza_tipo: "1", raza_txt: 'Spaniel de Agua Irlandés', is_active: true],
								[id_raza: 242, raza_tipo: "1", raza_txt: 'Spaniel de Pont-Audemer', is_active: true],
								[id_raza: 243, raza_tipo: "1", raza_txt: 'Spaniel de Sussex', is_active: true],
								[id_raza: 244, raza_tipo: "1", raza_txt: 'Spaniel Francés', is_active: true],
								[id_raza: 245, raza_tipo: "1", raza_txt: 'Spaniel japonés', is_active: true],
								[id_raza: 246, raza_tipo: "1", raza_txt: 'Spaniel Picardo', is_active: true],
								[id_raza: 247, raza_tipo: "1", raza_txt: 'Spitz Alemán', is_active: true],
								[id_raza: 248, raza_tipo: "1", raza_txt: 'Spitz de Norrbotten', is_active: true],
								[id_raza: 249, raza_tipo: "1", raza_txt: 'Spitz Japonés Enano', is_active: true],
								[id_raza: 250, raza_tipo: "1", raza_txt: 'Spitz Lobo', is_active: true],
								[id_raza: 251, raza_tipo: "1", raza_txt: 'Springer Spaniel Inglés', is_active: true],
								[id_raza: 252, raza_tipo: "1", raza_txt: 'Stabyhon (Perdiguero Frisón)', is_active: true],
								[id_raza: 253, raza_tipo: "1", raza_txt: 'Staffordshire Bull Terrier', is_active: true],
								[id_raza: 254, raza_tipo: "1", raza_txt: 'Tchuvatch Eslovaco', is_active: true],
								[id_raza: 255, raza_tipo: "1", raza_txt: 'Teckel', is_active: true],
								[id_raza: 256, raza_tipo: "1", raza_txt: 'Tejonero Alpino', is_active: true],
								[id_raza: 257, raza_tipo: "1", raza_txt: 'Terranova', is_active: true],
								[id_raza: 258, raza_tipo: "1", raza_txt: 'Terrier americano sin pelo', is_active: true],
								[id_raza: 259, raza_tipo: "1", raza_txt: 'Terrier Australiano', is_active: true],
								[id_raza: 260, raza_tipo: "1", raza_txt: 'Terrier Brasileño', is_active: true],
								[id_raza: 261, raza_tipo: "1", raza_txt: 'Terrier Cazador Alemán', is_active: true],
								[id_raza: 262, raza_tipo: "1", raza_txt: 'Terrier Checo', is_active: true],
								[id_raza: 263, raza_tipo: "1", raza_txt: 'Terrier de Airedale', is_active: true],
								[id_raza: 264, raza_tipo: "1", raza_txt: 'Terrier de Norfolk', is_active: true],
								[id_raza: 265, raza_tipo: "1", raza_txt: 'Terrier de Norwich', is_active: true],
								[id_raza: 266, raza_tipo: "1", raza_txt: 'Terrier de Skye', is_active: true],
								[id_raza: 267, raza_tipo: "1", raza_txt: 'Terrier Escocés', is_active: true],
								[id_raza: 268, raza_tipo: "1", raza_txt: 'Terrier Galés', is_active: true],
								[id_raza: 269, raza_tipo: "1", raza_txt: 'Terrier Irlendés', is_active: true],
								[id_raza: 270, raza_tipo: "1", raza_txt: 'Terrier Japonés', is_active: true],
								[id_raza: 271, raza_tipo: "1", raza_txt: 'Terrier Ruso Negro', is_active: true],
								[id_raza: 272, raza_tipo: "1", raza_txt: 'Terrier Tibetano', is_active: true],
								[id_raza: 273, raza_tipo: "1", raza_txt: 'Tosa Inu', is_active: true],
								[id_raza: 274, raza_tipo: "1", raza_txt: 'Toy Terrier Ruso', is_active: true],
								[id_raza: 275, raza_tipo: "1", raza_txt: 'Vallhund Sueco', is_active: true],
								[id_raza: 276, raza_tipo: "1", raza_txt: 'Vizsla', is_active: true],
								[id_raza: 277, raza_tipo: "1", raza_txt: 'Volpino Italiano', is_active: true],
								[id_raza: 278, raza_tipo: "1", raza_txt: 'West Highland White Terrier', is_active: true],
								[id_raza: 279, raza_tipo: "1", raza_txt: 'Wheaten Terrier', is_active: true],
								[id_raza: 280, raza_tipo: "1", raza_txt: 'Whippet', is_active: true],
								[id_raza: 281, raza_tipo: "1", raza_txt: 'Wolfhound Irlendés', is_active: true],
								[id_raza: 282, raza_tipo: "1", raza_txt: 'Yorkshire Terrier', is_active: true],
								[id_raza: 283, raza_tipo: "2", raza_txt: 'Abisinio', is_active: true],
								[id_raza: 284, raza_tipo: "2", raza_txt: 'American Curl', is_active: true],
								[id_raza: 285, raza_tipo: "2", raza_txt: 'Azul ruso', is_active: true],
								[id_raza: 286, raza_tipo: "2", raza_txt: 'American shorthair', is_active: true],
								[id_raza: 287, raza_tipo: "2", raza_txt: 'American wirehair', is_active: true],
								[id_raza: 288, raza_tipo: "2", raza_txt: 'Angora turco', is_active: true],
								[id_raza: 289, raza_tipo: "2", raza_txt: 'Africano doméstico', is_active: true],
								[id_raza: 290, raza_tipo: "2", raza_txt: 'Bengala', is_active: true],
								[id_raza: 291, raza_tipo: "2", raza_txt: 'Bobtail japonés', is_active: true],
								[id_raza: 292, raza_tipo: "2", raza_txt: 'Bombay', is_active: true],
								[id_raza: 293, raza_tipo: "2", raza_txt: 'Bosque de Noruega', is_active: true],
								[id_raza: 294, raza_tipo: "2", raza_txt: 'Brazilian Shorthair', is_active: true],
								[id_raza: 295, raza_tipo: "2", raza_txt: 'Brivon de pelo corto', is_active: true],
								[id_raza: 296, raza_tipo: "2", raza_txt: 'Brivon de pelo largo', is_active: true],
								[id_raza: 297, raza_tipo: "2", raza_txt: 'British Shorthair', is_active: true],
								[id_raza: 298, raza_tipo: "2", raza_txt: 'Burmés', is_active: true],
								[id_raza: 299, raza_tipo: "2", raza_txt: 'Burmilla', is_active: true],
								[id_raza: 300, raza_tipo: "2", raza_txt: 'Cornish rex', is_active: true],
								[id_raza: 301, raza_tipo: "2", raza_txt: 'California Spangled', is_active: true],
								[id_raza: 302, raza_tipo: "2", raza_txt: 'Cymric', is_active: true],
								[id_raza: 303, raza_tipo: "2", raza_txt: 'Chartreux', is_active: true],
								[id_raza: 304, raza_tipo: "2", raza_txt: 'Carex', is_active: true],
								[id_raza: 305, raza_tipo: "2", raza_txt: 'Deutsch Langhaar', is_active: true],
								[id_raza: 306, raza_tipo: "2", raza_txt: 'Devon rex', is_active: true],
								[id_raza: 307, raza_tipo: "2", raza_txt: 'Dorado africano', is_active: true],
								[id_raza: 308, raza_tipo: "2", raza_txt: 'Don Sphynx', is_active: true],
								[id_raza: 309, raza_tipo: "2", raza_txt: 'Dragon Li', is_active: true],
								[id_raza: 310, raza_tipo: "2", raza_txt: 'Europeo Común', is_active: true],
								[id_raza: 311, raza_tipo: "2", raza_txt: 'Exótico de Pelo Corto', is_active: true],
								[id_raza: 312, raza_tipo: "2", raza_txt: 'Gato europeo bicolor', is_active: true],
								[id_raza: 313, raza_tipo: "2", raza_txt: 'FoldEx', is_active: true],
								[id_raza: 314, raza_tipo: "2", raza_txt: 'German Rex', is_active: true],
								[id_raza: 315, raza_tipo: "2", raza_txt: 'Habana brown', is_active: true],
								[id_raza: 316, raza_tipo: "2", raza_txt: 'Himalayo', is_active: true],
								[id_raza: 317, raza_tipo: "2", raza_txt: 'Korat', is_active: true],
								[id_raza: 318, raza_tipo: "2", raza_txt: 'Khao Manee', is_active: true],
								[id_raza: 319, raza_tipo: "2", raza_txt: 'Maine Coon', is_active: true],
								[id_raza: 320, raza_tipo: "2", raza_txt: 'Manx', is_active: true],
								[id_raza: 321, raza_tipo: "2", raza_txt: 'Mau egipcio', is_active: true],
								[id_raza: 322, raza_tipo: "2", raza_txt: 'Munchkin', is_active: true],
								[id_raza: 323, raza_tipo: "2", raza_txt: 'Ocicat', is_active: true],
								[id_raza: 324, raza_tipo: "2", raza_txt: 'Oriental', is_active: true],
								[id_raza: 325, raza_tipo: "2", raza_txt: 'Oriental de pelo largo', is_active: true],
								[id_raza: 326, raza_tipo: "2", raza_txt: 'PerFold1​', is_active: true],
								[id_raza: 327, raza_tipo: "2", raza_txt: 'Persa Americano o Moderno', is_active: true],
								[id_raza: 328, raza_tipo: "2", raza_txt: 'Persa Clásico o Tradicional2​', is_active: true],
								[id_raza: 329, raza_tipo: "2", raza_txt: 'Peterbald', is_active: true],
								[id_raza: 330, raza_tipo: "2", raza_txt: 'Pixie Bob', is_active: true],
								[id_raza: 331, raza_tipo: "2", raza_txt: 'Ragdoll', is_active: true],
								[id_raza: 332, raza_tipo: "2", raza_txt: 'Sagrado de Birmania', is_active: true],
								[id_raza: 333, raza_tipo: "2", raza_txt: 'Scottish Fold', is_active: true],
								[id_raza: 334, raza_tipo: "2", raza_txt: 'Selkirk rex', is_active: true],
								[id_raza: 335, raza_tipo: "2", raza_txt: 'Serengeti', is_active: true],
								[id_raza: 336, raza_tipo: "2", raza_txt: 'Seychellois', is_active: true],
								[id_raza: 337, raza_tipo: "2", raza_txt: 'Siamés', is_active: true],
								[id_raza: 338, raza_tipo: "2", raza_txt: 'Siamés Moderno', is_active: true],
								[id_raza: 339, raza_tipo: "2", raza_txt: 'Siamés Tradicional', is_active: true],
								[id_raza: 340, raza_tipo: "2", raza_txt: 'Siberiano', is_active: true],
								[id_raza: 341, raza_tipo: "2", raza_txt: 'Snowshoe', is_active: true],
								[id_raza: 342, raza_tipo: "2", raza_txt: 'Sphynx', is_active: true],
								[id_raza: 343, raza_tipo: "2", raza_txt: 'Tonkinés', is_active: true],
								[id_raza: 344, raza_tipo: "2", raza_txt: 'Van Turco', is_active: true]
							]

				lista.forEach{item->sql.execute("INSERT INTO razas values (${item.id_raza}, ${item.raza_tipo}, ${item.raza_txt}, ${item.is_active})")}
			}
		}
	}
}